packages/scripts/scripts/utils/configs.js, packages/scripts/scripts/utils/configureTypescript.js
Standalon lib broke if storybook/cypress was included. This correctly sets up typescript for when there are multilple "roots" apart from src and only src folder.
<details>
<br />
```bash
npm install @tablecheck/scripts@1.1.4-canary.14.50473522e39f23b3cf9f581567f5b5e9181b90ae.0
yarn add @tablecheck/scripts@1.1.4-canary.14.50473522e39f23b3cf9f581567f5b5e9181b90ae.0
```
</details>
=> fix(scripts): correctly build standalone libraries

packages/scripts/scripts/utils/configureTypescript.js, packages/scripts/scripts/utils/validateEslintrc.js
Fixing an issue where the lib version of config typescript was missing some parts used in the app configure so the config didn't work.
Also fix the file path for the reset in validate eslintrc.
<details>
<br />
```bash
npm install @tablecheck/scripts@1.1.5-canary.17.41f64a1abe85c45cf2f752a99d36520b524ff6cf.0
yarn add @tablecheck/scripts@1.1.5-canary.17.41f64a1abe85c45cf2f752a99d36520b524ff6cf.0
```
</details>
=> fix(scripts): correctly init tsconfig for cypress in lib projects

.eslintignore, auditjs.json, packages/eslint-config/overrides/cypress.js, packages/scripts/cypressComponentTesting.d.ts, packages/scripts/cypressComponentTesting.js, packages/scripts/cypressComponentTesting.stories.mdx, packages/scripts/package.json, packages/scripts/razzle/sspa.js, packages/scripts/scripts/init.js, packages/scripts/templates/cypress.json
Update razzle sspa config to inject the app version into manifest automaticaly.
Add shared cypress component testing configuration utils and fixing some eslint rules for cypress.
<details>
<br />
```bash
npm install @tablecheck/eslint-config@1.2.0-canary.18.4e7d008cbb4e314d16bcce66958948b9156cc753.0
npm install @tablecheck/scripts@1.2.0-canary.18.4e7d008cbb4e314d16bcce66958948b9156cc753.0
yarn add @tablecheck/eslint-config@1.2.0-canary.18.4e7d008cbb4e314d16bcce66958948b9156cc753.0
yarn add @tablecheck/scripts@1.2.0-canary.18.4e7d008cbb4e314d16bcce66958948b9156cc753.0
```
</details>
=> feat(scripts): cypress component testing + razzle config

.autorc, .github/workflows/label_checker.yml, .github/workflows/release.yml, package-lock.json, package.json
Attempting fix from https://github.com/intuit/auto/issues/1030
Also implementing FL-464
<details>
<br />
```bash
npm install @tablecheck/eslint-config@1.2.0-canary.20.659b35688f1eb28a1d75986d6015b16e70a7a897.0
npm install @tablecheck/scripts@1.2.0-canary.20.659b35688f1eb28a1d75986d6015b16e70a7a897.0
yarn add @tablecheck/eslint-config@1.2.0-canary.20.659b35688f1eb28a1d75986d6015b16e70a7a897.0
yarn add @tablecheck/scripts@1.2.0-canary.20.659b35688f1eb28a1d75986d6015b16e70a7a897.0
```
</details>
=> fix: release process

packages/eslint-config/rules/namingConvention.js
This allows the more syntactically readable past tense versions of certain boolean prefixes.
* `isPrevSelected` => `wasSelected`
* `hasPrevSelection` => `hadSelection`
<details>
<br />
```bash
npm install @tablecheck/eslint-config@1.3.0-canary.23.d3869a98864d6f21859a1b7c4ecc9f3ac8c30350.0
npm install @tablecheck/scripts@1.3.0-canary.23.d3869a98864d6f21859a1b7c4ecc9f3ac8c30350.0
yarn add @tablecheck/eslint-config@1.3.0-canary.23.d3869a98864d6f21859a1b7c4ecc9f3ac8c30350.0
yarn add @tablecheck/scripts@1.3.0-canary.23.d3869a98864d6f21859a1b7c4ecc9f3ac8c30350.0
```
</details>
=> feat(eslint-config): add past tense boolean prefixes

packages/scripts/scripts/auditjs.js
On some system latest audit version uses root folder as target
for cache output. Providing cache option to cli args fixes the issue
<details>
<br />
```bash
npm install @tablecheck/scripts@1.5.0-canary.26.9e88af10d104c1f8c28870af1da9e5aa15ed95c1.0
yarn add @tablecheck/scripts@1.5.0-canary.26.9e88af10d104c1f8c28870af1da9e5aa15ed95c1.0
```
</details>
=> fix(scripts): add audit cli cache option

packages/scripts/scripts/init.js, packages/scripts/scripts/utils/configureTypescript.js
When the git root and the package.json are not in the same folder typescript doesn't correctly detect our usage of typescript like other projects do.
Also adding in some extra checks and updates to the init scripts.
<details>
<br />
```bash
npm install @tablecheck/scripts@1.5.1-canary.27.2ddfba904a168e97e40a6ad639c07c3ded844e61.0
yarn add @tablecheck/scripts@1.5.1-canary.27.2ddfba904a168e97e40a6ad639c07c3ded844e61.0
```
</details>
=> fix: add cypress types for odd edge cases

packages/eslint-config/rules/react.js
Reason: Typescript makes it better. Eslint may not figure them out properly in case of deeply nested interfaces (generic)
<details>
<br />
```bash
npm install @tablecheck/eslint-config@1.5.0-canary.28.ea0962c958aa5c2cbeec2a7380ef6d5557264883.0
npm install @tablecheck/scripts@1.6.0-canary.28.ea0962c958aa5c2cbeec2a7380ef6d5557264883.0
yarn add @tablecheck/eslint-config@1.5.0-canary.28.ea0962c958aa5c2cbeec2a7380ef6d5557264883.0
yarn add @tablecheck/scripts@1.6.0-canary.28.ea0962c958aa5c2cbeec2a7380ef6d5557264883.0
```
</details>
=> fix(scripts): turn off prop types rule

packages/eslint-config/overrides/cypress.js
Sometimes the lint-staged eslint couldn't find the cypress configs correctly, this fixes that issue.
<details>
<br />
```bash
npm install @tablecheck/eslint-config@1.5.1-canary.29.efab3d29f4cf489567f85982e3735009bb6db61a.0
npm install @tablecheck/scripts@1.6.1-canary.29.efab3d29f4cf489567f85982e3735009bb6db61a.0
yarn add @tablecheck/eslint-config@1.5.1-canary.29.efab3d29f4cf489567f85982e3735009bb6db61a.0
yarn add @tablecheck/scripts@1.6.1-canary.29.efab3d29f4cf489567f85982e3735009bb6db61a.0
```
</details>
=> fix: eslint plugin can't find tsconfig in precommit

auditjs.json, packages/semantic-release-config/README.md, packages/semantic-release-config/README.stories.mdx, packages/semantic-release-config/index.js, packages/semantic-release-config/package.json
BREAKING-CHANGE: no longer supports gitlab, only github
This is to support moving our codebases from gitlab to GitHub
<details>
<br />
```bash
npm install @tablecheck/semantic-release-config@2.0.0-canary.31.200a1ba6b2e84277bca8149dc7e11e742a56c683.0
yarn add @tablecheck/semantic-release-config@2.0.0-canary.31.200a1ba6b2e84277bca8149dc7e11e742a56c683.0
```
</details>
=> feat(semantic-release-config): change gitlab to github

packages/scripts/scripts/utils/configureTypescript.js
This fixes the issue with needing relative paths in cypress component tests that become extremely long.
The new import path is `import '#cypress/support/commands'` at present.
Reasoning is as follows;
* Straight `import 'cypress/support/commands'` is a little unclear as unlike our other absolute path imports this folder isn't a child of './src'. Also it clashes with the actual cypress package `import { CyHttpMessages } from 'cypress/types/net-stubbing';`
* Abbreviations like `cy` are also unclear as this again is often used by cypress usage/implementation (not as a package though)
* `local-cypress` instead of `#cypress` is also up for debate, I prefer the `#` as it's shorter and more clear that it's different.
<details>
<summary>📦 Published PR as canary version: <code>Canary …
=> feat(scripts): support absolute path for cypress folder

packages/scripts/scripts/utils/configureTypescript.js
Renaming of paths to compilerPaths in previous PR caused errors to occur.
In version 1.8.0 the following error occurs on install and the whole npm install fails.
```
npm ERR! code 1
npm ERR! path /Users/simeon.cheeseman/Development/settings-frontend/node_modules/@tablecheck/scripts
npm ERR! command failed
npm ERR! command sh -c ./bin/postinstall.js
npm ERR! Generating definition file for node-config...  Done!
npm ERR! node:internal/validators:119
npm ERR!     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
npm ERR!     ^
npm ERR! 
npm ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
npm ERR!     at new NodeError (node:internal/errors:363:5)
npm ERR!     at validateString (node:internal/validators:119:11)
npm ERR!     at …
```
=> fix(scripts): revert bad variable rename

packages/scripts/scripts/utils/configureTypescript.js
Fixes an issue where cypress didn't know about any definition files in the src folder causing errors in some cases.
<details>
<br />
```bash
npm install @tablecheck/scripts@1.8.2-canary.35.63da3bc43fcaca62ffc15365f228145018e5f383.0
yarn add @tablecheck/scripts@1.8.2-canary.35.63da3bc43fcaca62ffc15365f228145018e5f383.0
```
</details>
=> fix(scripts): typescript config for cypress

packages/semantic-release-config/index.js, packages/semantic-release-config/package.json
Adding an exec step on success to write a version.txt file that can be read by CI utilities or other tools. This is a more generic version of the custom script that was used in settings-frontend.
We are using a file as this can often be passed between different CI jobs far more easily than an environment variable or similar. Also as we rely 100% on tags and not the package.json version for our versioning we can't just re-read the package.json file again.
<details>
<br />
```bash
npm install @tablecheck/semantic-release-config@2.1.0-canary.37.b2e88a59c5d0835661fc74951ad67f1d2ce5746f.0
yarn add @tablecheck/semantic-release-config@2.1.0-canary.37.b2e88a59c5d0835661fc74951 …
```
=> feat(semantic-release-config): add CI utility output file

packages/semantic-release-config/README.md, packages/semantic-release-config/README.stories.mdx
Latest feature was missing documentation (I had this locally but forgot to commit for some reason)
=> docs: update semantic-release-config readme

packages/scripts/scripts/lint.js, packages/scripts/scripts/utils/package.js, packages/scripts/scripts/utils/runEslint.js, packages/scripts/tests/dependencyValidation.spec.js
Fixes a bug where the lint script would pass and exit with 0 even if there were eslint errors.
<details>
<br />
```bash
npm install @tablecheck/scripts@1.9.1-canary.38.7a88e8b81e009061cd1d3cde4abd9376e44ceac4.0
npm install @tablecheck/semantic-release-config@2.1.1-canary.38.7a88e8b81e009061cd1d3cde4abd9376e44ceac4.0
yarn add @tablecheck/scripts@1.9.1-canary.38.7a88e8b81e009061cd1d3cde4abd9376e44ceac4.0
yarn add @tablecheck/semantic-release-config@2.1.1-canary.38.7a88e8b81e009061cd1d3cde4abd9376e44ceac4.0
```
</details>
=> fix(scripts): correctly fail runLint when errors are present

package-lock.json, packages/semantic-release-config/package.json
Updating with the changes from https://github.com/juliuscc/semantic-release-slack-bot/pull/79
<details>
<br />
```bash
npm install @tablecheck/semantic-release-config@2.2.0-canary.40.d35a31e29995e48b90f74d7f4e22853b44f6ddc5.0
yarn add @tablecheck/semantic-release-config@2.2.0-canary.40.d35a31e29995e48b90f74d7f4e22853b44f6ddc5.0
```
</details>
=> fix(semantic-release-config): update internal versions

package-lock.json, package.json, packages/scripts/scripts/init.js
Mainly updating storybook to a version with a more strict version of colors.js
fixes #41
<details>
<br />
```bash
npm install @tablecheck/scripts@1.10.0-canary.42.10c13201cd3487bd5b4db749af522e8a8e84cafd.0
npm install @tablecheck/semantic-release-config@2.4.0-canary.42.10c13201cd3487bd5b4db749af522e8a8e84cafd.0
yarn add @tablecheck/scripts@1.10.0-canary.42.10c13201cd3487bd5b4db749af522e8a8e84cafd.0
yarn add @tablecheck/semantic-release-config@2.4.0-canary.42.10c13201cd3487bd5b4db749af522e8a8e84cafd.0
```
</details>
=> security: update dependencies

packages/semantic-release-config/README.md, packages/semantic-release-config/README.stories.mdx, packages/semantic-release-config/package.json, packages/semantic-release-config/with-npm-publish/package.json, packages/semantic-release-config/withNpmPublish.js
Used for publishing to any npm repository as part of the semantic-release step. Currently semantic-release configs don't allow partial extension, so we would need to manually extend the config to use it in our applications.
<details>
<br />
```bash
npm install @tablecheck/semantic-release-config@2.4.0-canary.46.c432086551b83b1afa13b56f00cdda9d58d8dadd.0
yarn add @tablecheck/semantic-release-config@2.4.0-canary.46.c432086551b83b1afa13b56f00cdda9d58d8dadd.0
```
</details>
=> feat: add semantic-release config including npm publish

packages/eslint-config/rules/react.js, packages/eslint-plugin/__tests__/consistentReactImport.test.js, packages/eslint-plugin/package.json, packages/eslint-plugin/src/consistentReactImport.js
Fixes #49
Additionally enabled consistent fragment usage.
<details>
<br />
```bash
npm install @tablecheck/eslint-config@1.7.1-canary.50.2051540977.0
npm install @tablecheck/eslint-plugin@1.2.1-canary.50.2051540977.0
npm install @tablecheck/scripts@1.11.1-canary.50.2051540977.0
yarn add @tablecheck/eslint-config@1.7.1-canary.50.2051540977.0
yarn add @tablecheck/eslint-plugin@1.2.1-canary.50.2051540977.0
yarn add @tablecheck/scripts@1.11.1-canary.50.2051540977.0
```
</details>
=> fix(eslint-plugin): correctly handle jsx fragments

packages/scripts/scripts/utils/configureTypescript.js
Fixes the config options that prevented eslint errors and weird typescript errors in both `src/**/*.cypress.tsx?` files and all files inside the cypress bundle.
This should have only affected usage within IDEs like vscode and not the lint script itself.
<details>
<br />
```bash
npm install @tablecheck/scripts@1.11.2-canary.52.2164645099.0
yarn add @tablecheck/scripts@1.11.2-canary.52.2164645099.0
```
</details>
=> fix(scripts): eslint and typescript work correctly in cypress files

README.md, package-lock.json, package.json, packages/scripts/scripts/test.js, packages/scripts/scripts/test.stories.mdx, packages/scripts/scripts/utils/argv.js
Fixing some bugs and issues arising from using https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest
Fixes the storybook build which was missing a plugin dependency
<details>
<br />
```bash
npm install @tablecheck/scripts@1.12.0-canary.55.2231386425.0
yarn add @tablecheck/scripts@1.12.0-canary.55.2231386425.0
```
</details>
=> fix(scripts): compatability with 3rd party jest tools

packages/scripts/config/storybook.main.js, packages/scripts/package.json, packages/scripts/templates/.storybook/main.js
Fixing babel issues with latest storybook, if there you had a `.storybook/.babelrc` file to fix babel issues it can be deleted as it should no longer be necessary.
<details>
<br />
```bash
npm install @tablecheck/scripts@1.12.1-canary.59.2306364484.0
yarn add @tablecheck/scripts@1.12.1-canary.59.2306364484.0
```
</details>
=> fix(scripts): fix compatibilty issues with latest storybook

packages/eslint-config/index.js, packages/eslint-config/overrides/maxLines.js
fixes #58
<details>
<br />
```bash
npm install @tablecheck/eslint-config@1.7.2-canary.60.2317081826.0
npm install @tablecheck/scripts@1.12.2-canary.60.2317081826.0
yarn add @tablecheck/eslint-config@1.7.2-canary.60.2317081826.0
yarn add @tablecheck/scripts@1.12.2-canary.60.2317081826.0
```
</details>
=> fix(eslint-config): override max lines for certain files

packages/scripts/scripts/utils/configureTypescript.js
This was a really dumb typo...
<details>
<br />
```bash
npm install @tablecheck/scripts@1.12.3-canary.61.2349661341.0
yarn add @tablecheck/scripts@1.12.3-canary.61.2349661341.0
```
</details>
=> fix: typo in “include”

packages/scripts/razzle/sspa.js
Changing our SSPA lib output from amd define to window var. This prevent us from clashing with define implementations of other libraries as ours was incomplete. This is simpler and less prone to breaking than the incomplete define plugin. Related to RFC-19
<details>
<br />
```bash
npm install @tablecheck/scripts@2.0.0-canary.63.2369157285.0
yarn add @tablecheck/scripts@2.0.0-canary.63.2369157285.0
```
</details>
=> fix(scripts): switch sspa library output to window

packages/scripts/scripts/rollup/buildPackage.js
For some of our older apps with some odd restrictions due to inability to upgrade build tools require an all inclusive es5 build as sub-dependencies are not loaded correctly. (Ember app)
This allows us to export an es5 single build js file.
<details>
<br />
```bash
npm install @tablecheck/scripts@2.1.0-canary.65.2425880340.0
yarn add @tablecheck/scripts@2.1.0-canary.65.2425880340.0
```
</details>
=> feat(scripts): add a all-inclusive es5 bundle build

auditjs.json, packages/scripts/scripts/utils/configureTypescript.js, packages/scripts/scripts/utils/writeCarbonIconTypes.js
If `@carbon/icons-react` at version 11 is installed, we will generate the type definitions automatically and add them to the tsconfig files definition.
<details>
<br />
```bash
npm install @tablecheck/scripts@2.2.0-canary.66.2546496273.0
yarn add @tablecheck/scripts@2.2.0-canary.66.2546496273.0
```
</details>
=> feat(scripts): add carbon icon types generation

package-lock.json, packages/scripts/package.json
v1.1.0 uses jest@28 and we haven't upgraded to that yet. See https://github.com/jest-community/jest-watch-typeahead/blob/main/CHANGELOG.md
<details>
<br />
```bash
npm install @tablecheck/scripts@2.2.1-canary.67.2553811532.0
yarn add @tablecheck/scripts@2.2.1-canary.67.2553811532.0
```
</details>
=> fix(scripts): change jest-watch-typeahead to be fixed to v1.0.0

auditjs.json, packages/scripts/scripts/utils/configureTypescript.js
An issue occured in tablekit-next where if there was only one typescript package the project build would fail with `Debug Failure. project /…/tablekit-next/tsconfig.json expected to have at least one output`
This PR fixes that issue by detecting if we are doing a "type check" (ie non-build) and if there is only one TS project in the lerna repo then we replace the top level config with a copy of the tsconfig in the child project so we then run a "single" run not a projects/workspace run (all paths are absolute so this has no issues).
<details>
<br />
```bash
npm install @tablecheck/scripts@2.3.1-canary.69.2751406635.0
yarn add …
```
=> fix(scripts): non build tsc would fail if there is only one project

auditjs.json, packages/scripts/scripts/precommit.js, packages/scripts/scripts/utils/package.js
Omiting the config param will correctly resolve to the same config as the normal lint. With the config param it’s resolving somewhere unknown.
<details>
<br />
```bash
npm install @tablecheck/scripts@2.3.3-canary.71.2787011566.0
yarn add @tablecheck/scripts@2.3.3-canary.71.2787011566.0
```
</details>
=> fix(scripts): precommit should use same configs as lint

packages/scripts/scripts/utils/configureTypescript.js
Cypress tsconfig.json in Lib setup was missing the types that were in app and eslint setups
<details>
<br />
```bash
npm install @tablecheck/scripts@2.3.5-canary.73.2910736695.0
yarn add @tablecheck/scripts@2.3.5-canary.73.2910736695.0
```
</details>
=> fix(scripts): typescript for cypress in libraries

packages/scripts/scripts/rollup/__snapshots__/jsxPlugin.spec.js.snap, packages/scripts/scripts/rollup/buildPackage.js, packages/scripts/scripts/rollup/fixtures/packageWithEmotionReact.json, packages/scripts/scripts/rollup/fixtures/packageWithReact.json, packages/scripts/scripts/rollup/jsxPlugin.js, packages/scripts/scripts/rollup/jsxPlugin.spec.js, packages/scripts/scripts/utils/package.js
For projects that do not have "@emotion/react" dependency use default react options for Babel "preset-react" plugin.
<details>
<br />
```bash
npm install @tablecheck/scripts@2.3.6-canary.74.2946446774.0
yarn add @tablecheck/scripts@2.3.6-canary.74.2946446774.0
```
</details>
=> fix(scripts): use correct Babel "preset-react" plugin options

auditjs.json, packages/scripts/razzle/base.js
Fixes #76
<details>
<br />
```bash
npm install @tablecheck/scripts@2.3.7-canary.77.3132920166.0
yarn add @tablecheck/scripts@2.3.7-canary.77.3132920166.0
```
</details>
=> fix: config issue

packages/eslint-config/package.json, packages/eslint-config/rules/react.js, packages/scripts/package.json
There are probably other changes that need to be taken to support react 18 fully, but most of it should work with current setup. Other changes will be done in next branch but this at least allows us to try out react 18 without the CI failing.
Specifically related to the TableKit next branch which has some installation issues due to this - canary version was tested here: https://github.com/tablecheck/tablekit/pull/131
<details>
<br />
```bash
npm install @tablecheck/eslint-config@1.8.2-canary.78.3156990612.0
npm install @tablecheck/scripts@2.3.8-canary.78.3156990612.0
yarn add @tablecheck/eslint-config@1.8.2-canary.78.3156990612.0
yarn add …
```
=> fix: loosen react dependency versions

.github/workflows/docs.yml, .github/workflows/pull_requests.yml, .github/workflows/release.yml, .npmrc, README.md, auditjs.json, packages/scripts/scripts/rollup/buildPackage.js
See this replay for the bug reproduction and comments https://app.replay.io/recording/replay-of-build-libjs--e54917c4-0962-4cbf-976f-f8ecae32ee91
New Resulting Regex;
Replace regex comparison;
<details>
<br />
```bash
npm install @tablecheck/scripts@2.3.9-canary.80.3475811983.0
yarn add @tablecheck/scripts@2.3.9-canary.80.3475811983.0
```
</details>
=> fix(scripts): correct path matcher regex for stripping lib types

auditjs.json, packages/scripts/scripts/rollup/buildPackage.js
This fixes absolute imports to files in the `.d.ts` output files which do not support file aliases, only relative imports.
```ts
// in file `src/foo/bar/sub.ts
import { a } from 'rootIndexFile';
// should be rewritten to the following
import { a } from '../../rootIndexFile';
```
<details>
<br />
```bash
npm install @tablecheck/scripts@2.3.10-canary.81.4499279437.0
yarn add @tablecheck/scripts@2.3.10-canary.81.4499279437.0
```
</details>
=> fix: lib-build correctly remaps root level absolute file imports

.github/setup/action.yml, .github/workflows/docs.yml, .github/workflows/pull_requests.yml, .github/workflows/release.yml, nx.json, packages/eslint-plugin/project.json, packages/eslint-plugin/vite.config.ts
* properly cache the result of tests so the same junit file is output and reported to the PR (requires vite config and nx config)
* cache build outputs so they can be restored
See https://github.com/tablecheck/tablecheck-react-system/actions/runs/6336490202/job/17209658997 (major label just in case as the last one failed to release)
<details>
<br />
```bash
npm install @tablecheck/frontend-audit@2.0.0-canary.84.6337128203.0
npm install @tablecheck/commitlint-config@2.0.0-canary.84.6337128203.0
npm install @tablecheck/eslint-config@2.0.0-canary.84.6337128203.0
npm install @tablecheck/eslint-plugin@2.0.0-canary.84.6337128203.0
npm install …
```
=> ci: fix nx branch setup

.github/setup/action.yml, .github/workflows/docs.yml, .github/workflows/release.yml, package.json, packages/eslint-config/src/overrides/buildBaseTypescript.ts, packages/eslint-plugin/__tests__/shortestImport.test.ts, packages/eslint-plugin/src/shortestImport.ts, packages/nx/src/generators/quality/eslintConfig.ts, packages/nx/src/generators/quality/files/.eslintrc.cjs, packages/nx/src/generators/quality/generator.ts, packages/nx/src/generators/quality/projectConfig.ts
Merged the release CI fixes from another branch here as I didn't figure out that one just needed the `npm run build:ci` changes to run properly 🤦 
<details>
<br />
```bash
npm install @tablecheck/frontend-audit@2.0.0-canary.86.6377429546.0
npm install @tablecheck/commitlint-config@2.0.0-canary.86.6377429546.0
npm install @tablecheck/eslint-config@2.0.0-canary.86.6377429546.0
npm install @tablecheck/eslint-plugin@2.0.0-canary.86.6377429546.0
npm install @tablecheck/nx@2.0.0-canary.86.6377429546.0
npm install @tablecheck/prettier-config@2.0.0-canary.86.6377429546.0
npm install @tablecheck/semantic-release-config@3.0.0-canary.86.6377429546.0
npm install …
```
=> fix: eslint needs extra configs to resolve paths correctly

packages/audit/package.json, packages/commitlint-config/package.json, packages/eslint-config/package.json, packages/eslint-plugin/__tests__/shortestImport.test.ts, packages/eslint-plugin/package.json, packages/eslint-plugin/src/shortestImport.ts, packages/nx/package.json, packages/prettier-config/package.json, packages/semantic-release-config/package.json, packages/utils/package.json
The issue was caused by a `.env` file at the tsconfig root which resolved to a `{ '': '...' }` in the alias mappings which matched _everything_.
Had troubling navigating around so cleaned up the code as well, this mainly affected `import ... from 'axios'` or similar npm level imports.
<details>
<br />
```bash
npm install @tablecheck/frontend-audit@2.0.1-canary.88.6467591840.0
npm install @tablecheck/commitlint-config@2.0.1-canary.88.6467591840.0
npm install @tablecheck/eslint-config@2.0.1-canary.88.6467591840.0
npm install @tablecheck/eslint-plugin@2.0.1-canary.88.6467591840.0
npm install @tablecheck/nx@2.0.1-canary.88.6467591840.0
npm install …
```
=> fix: shortest-import rule failed with .env file

auditjs.json, package-lock.json, package.json, packages/audit/src/index.ts, packages/audit/src/main.ts
No ticket
<details>
<br />
```bash
npm install @tablecheck/frontend-audit@5.0.1-canary.90.6503547560.0
yarn add @tablecheck/frontend-audit@5.0.1-canary.90.6503547560.0
```
</details>
=> fix: audit should exit based on success

package-lock.json, packages/eslint-config/package.json, packages/eslint-config/src/index.ts, packages/eslint-config/src/rules/react.ts
As we use Vite by default, this eslint rule will help with development and also keeping files consistent. The options to avoid this rule erroring are;
* Put all styled components/types/utils etc in the same file
* Put them in other `.style.ts` or `.types.ts` or basically a different file.
Trying this at a really strict level to start out and will downgrade to warn if it reports too many false positives.
<details>
<br />
```bash
npm install @tablecheck/eslint-config@8.1.0-canary.91.6527621571.0
yarn add @tablecheck/eslint-config@8.1.0-canary.91.6527621571.0
```
</details>
=> feat: add react-refresh eslint rules

packages/eslint-config/src/overrides/typescriptTests.ts
<details>
<br />
```bash
npm install @tablecheck/eslint-config@8.1.2-canary.94.6701033798.0
yarn add @tablecheck/eslint-config@8.1.2-canary.94.6701033798.0
```
</details>
=> fix: disable more rules in tests

packages/eslint-config/package.json, packages/nx/package.json
Updating dependencies that were out of date.
<details>
<br />
```bash
npm install @tablecheck/eslint-config@8.2.1-canary.95.6860547848.0
npm install @tablecheck/nx@6.1.1-canary.95.6860547848.0
yarn add @tablecheck/eslint-config@8.2.1-canary.95.6860547848.0
yarn add @tablecheck/nx@6.1.1-canary.95.6860547848.0
```
</details>
=> fix: loosen eslint-config dependency version

packages/eslint-config/src/overrides/storybook.ts, packages/eslint-config/src/presets/basic.ts, packages/eslint-config/src/presets/cypressComponent.ts, packages/eslint-config/src/presets/reactTs.ts, packages/eslint-config/src/presets/typescript.ts, packages/nx/src/generators/quality/eslintConfig.ts
<details>
<br />
```bash
npm install @tablecheck/eslint-config@8.2.2-canary.96.6888659418.0
npm install @tablecheck/nx@6.1.2-canary.96.6888659418.0
yarn add @tablecheck/eslint-config@8.2.2-canary.96.6888659418.0
yarn add @tablecheck/nx@6.1.2-canary.96.6888659418.0
```
</details>
=> fix: eslint configs/presets and setup

packages/nx/src/generators/quality/eslintConfig.ts, packages/nx/src/generators/quality/schema.json
Supports setting cypress component testing and storybook use independantly of the base extension setting.
<details>
<br />
```bash
npm install @tablecheck/nx@6.1.3-canary.98.7162348418.0
yarn add @tablecheck/nx@6.1.3-canary.98.7162348418.0
```
</details>
=> fix(nx): quality generator should use more generic tsconfig definition

packages/nx/src/generators/quality/eslintConfig.ts, packages/nx/src/generators/quality/generator.ts, packages/nx/src/generators/ts-carbon-icons/generator.ts, packages/nx/src/generators/ts-node-config/generator.ts, packages/nx/src/utils/tempFiles.ts
Without this change we would write the files even in dry-mode. This meant that the “preview” of the generate UI would change files!!
<details>
<br />
```bash
npm install @tablecheck/nx@6.1.3-canary.99.7205549679.0
yarn add @tablecheck/nx@6.1.3-canary.99.7205549679.0
```
</details>
=> fix(nx): generators correctly respect “dry-run”

auditjs.json, package-lock.json, packages/nx/src/generators/quality/eslintConfig.ts
<details>
<br />
```bash
npm install @tablecheck/nx@6.1.4-canary.100.7485085795.0
yarn add @tablecheck/nx@6.1.4-canary.100.7485085795.0
```
</details>
=> fix(nx): eslint config generation should use relative paths

packages/prettier-config/config.json
This is a safety config for an issue introduced in prettier 3.2.2
See https://github.com/prettier/prettier/issues/15956#issuecomment-1905768038
<details>
<br />
```bash
npm install @tablecheck/prettier-config@4.0.1-canary.101.7664911459.0
yarn add @tablecheck/prettier-config@4.0.1-canary.101.7664911459.0
```
</details>
=> fix: handle prettier formatting of certain json files

package.json, packages/audit/package.json, packages/commitlint-config/package.json, packages/eslint-config/package.json, packages/eslint-config/src/overrides/cypress.ts, packages/eslint-config/src/overrides/storybook.ts, packages/eslint-config/src/overrides/typescriptDocumentation.ts, packages/eslint-config/src/presets/cypressInternal.ts, packages/eslint-config/src/presets/typescript.ts, packages/eslint-plugin/package.json, packages/semantic-release-config/package.json
```ts
const a: any;
const b = a; // throws eslint error
```
In this scenario, usually we should avoid this. In the case of tests, typescript definition files and storybook, we allow `any` so it makes sense to turn off this rule.
<details>
<br />
```bash
npm install @tablecheck/frontend-audit@6.0.1-canary.104.7707943839.0
npm install @tablecheck/commitlint-config@6.0.1-canary.104.7707943839.0
npm install @tablecheck/eslint-config@8.2.5-canary.104.7707943839.0
npm install @tablecheck/eslint-plugin@6.1.2-canary.104.7707943839.0
npm install @tablecheck/semantic-release-config@7.0.1-canary.104.7707943839.0
yarn add @tablecheck/frontend-audit@6.0.1-canary.104.7707943839.0 …
```
=> fix: disable @typescript-eslint/no-unsafe-assignment where any is allowed

package-lock.json, packages/commitlint-config/formatters/junit.js, packages/commitlint-config/package.json
Moving changes from https://github.com/davidparsson/junit-report-builder/pull/61
Sample output:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Commit Lint" tests="2" failures="0" errors="2" skipped="0">
<testsuite name="some bad commit" tests="2" failures="0" errors="2" skipped="0">
<testcase name="subject-empty" classname="Error">
<error message="subject may not be empty"/>
</testcase>
<testcase name="type-empty" classname="Error">
<error message="type may not be empty"/>
</testcase>
</testsuite>
</testsuites>
```
<details>
<br />
```bash
npm install @tablecheck/commitlint-config@6.0.2-canary.105.7750623779.0
yarn add …
```
=> fix(commitlint-config): junit formatter updated to include top level title

packages/audit/project.json, packages/commitlint-config/project.json, packages/eslint-config/project.json, packages/eslint-config/src/overrides/buildBaseTypescript.ts, packages/eslint-plugin/project.json, packages/nx/project.json, packages/nx/src/generators/quality/projectConfig.ts, packages/semantic-release-config/project.json
See https://www.totaltypescript.com/method-shorthand-syntax-considered-harmful
<details>
<br />
```bash
npm install @tablecheck/frontend-audit@6.1.0-canary.106.7795884210.0
npm install @tablecheck/commitlint-config@6.1.0-canary.106.7795884210.0
npm install @tablecheck/eslint-config@8.3.0-canary.106.7795884210.0
npm install @tablecheck/eslint-plugin@6.2.0-canary.106.7795884210.0
npm install @tablecheck/nx@6.2.0-canary.106.7795884210.0
npm install @tablecheck/semantic-release-config@7.1.0-canary.106.7795884210.0
yarn add @tablecheck/frontend-audit@6.1.0-canary.106.7795884210.0
yarn add @tablecheck/commitlint-config@6.1.0-canary.106.7795884210.0
yarn add …
```
=> fix: add method signature style error

.prettierignore, packages/eslint-config/src/rules/namingConvention.ts, packages/eslint-config/tests/namingConvention.ts/variables.tsx
The `_destroy: true` property is used as a special key in monolith/ruby-on-rails APIs to indicate that the sub-record should be destroyed so we should allow this specific exception.
We have a _ton_ of "eslint-disable" comments related to this in our repos.
<details>
<br />
```bash
npm install @tablecheck/eslint-config@8.5.0-canary.108.8504387473.0
yarn add @tablecheck/eslint-config@8.5.0-canary.108.8504387473.0
```
</details>
=> feat: allow `_destroy` as a property

packages/eslint-config/src/rules/react.ts
There's a auto-fixable rule for this "footgun", so we should enable it seeing as it already exists.
See;
* https://stackoverflow.com/a/65713598
* https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-leaked-render.md
* https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx
<details>
<br />
```bash
npm install @tablecheck/eslint-config@9.0.1-canary.111.10052710064.0
yarn add @tablecheck/eslint-config@9.0.1-canary.111.10052710064.0
```
</details>
=> feat: add react rule for no leaked rendering

package-lock.json, packages/audit/src/index.ts, packages/eslint-config/package.json, packages/eslint-config/src/index.ts, packages/eslint-config/src/overrides/buildBaseTypescript.ts, packages/eslint-config/src/overrides/cypress.ts, packages/eslint-config/src/presets/basic.ts, packages/eslint-config/src/rules/general.ts, packages/eslint-plugin/__tests__/forbiddenImports.test.ts, packages/eslint-plugin/__tests__/shortestImport.test.ts, packages/eslint-plugin/src/consistentReactImport.ts, packages/eslint-plugin/src/forbiddenImports.ts, packages/eslint-plugin/src/shortestImport.ts, packages/nx/src/executors/publint/executor.ts, packages/nx/src/executors/quality/executor.ts, packages/nx/src/generators/quality/eslintConfig.ts, packages/nx/src/generators/quality/generator.ts, packages/nx/src/generators/quality/projectConfig.ts, packages/nx/src/generators/ts-carbon-icons/generator.ts, packages/nx/src/generators/ts-file-types/generator.ts, packages/nx/src/generators/ts-node-config/generator.ts, packages/nx/src/generators/vite-lib/generator.ts, packages/nx/src/utils/nx.ts, packages/nx/src/utils/packageJson.ts, packages/nx/src/utils/tempFiles.ts
* Use a new [import sorting plugin](https://www.npmjs.com/package/eslint-plugin-simple-import-sort) that also sorts inside the `{}` of an import
* Add the ["force using `type`" annotations](https://typescript-eslint.io/rules/consistent-type-imports/) rule to reduce bundle sizing and ease code splitting (using the inline version to keep the number of imports down)
See https://github.com/tablecheck/settings-frontend/pull/967#discussion_r1678656187
<details>
<br />
```bash
npm install @tablecheck/frontend-audit@6.2.0-canary.112.10156623768.0
npm install @tablecheck/eslint-config@9.2.0-canary.112.10156623768.0
npm install …
```
=> feat: add and replace stylistic rules around imports

packages/vite-import-massager-plugin/src/index.spec.ts, packages/vite-import-massager-plugin/src/index.ts
This to support fixing our TableKit exports.
```ts
new ImportMassagerPlugin([
{
packageName: '@tablecheck/tablekit-react',
importTransform: (importName) => {
const importPath = tablekitEsmMap.get(importName);
if (importPath) return importPath;
const defaultImportPath = tablekitEsmMap.get('default');
const startsWithKey = tablekitEsmMapKeys.find(
(k) =>
importName.toLowerCase().startsWith(k.toLowerCase()) ||
`Variant${k}` === importName,
);
if (startsWithKey)
return (
tablekitEsmMap.get(startsWithKey) ??
defaultImportPath ??
importName
);
return defaultImportPath ?? `/${importName}`;
},
exportTransform: (exportName, alias) =>
alias ? `{${exportName} as ${alias}}` : `{ ${exportName} }`,
},
{
transformPackages: ['@tablecheck'],
packageName: '@tablecheck/tablekit-core',
importTransform: …
```
=> feat: adds support for non-default exported import remapping

packages/eslint-config/src/overrides/buildBaseTypescript.ts
<details>
<br />
```bash
npm install @tablecheck/eslint-config@10.1.0-canary.116.11452183036.0
yarn add @tablecheck/eslint-config@10.1.0-canary.116.11452183036.0
```
</details>
=> feat(eslint-config): add ts rule to enforce member accessibility in classes

package-lock.json, packages/eslint-config/package.json
To update to NXv19 in DPOR, `ts-eslint` v7 is suggested but `eslint-config-airbnb-typescript `has the following peerDeps:
-     "@typescript-eslint/eslint-plugin": "^5.13.0 || ^6.0.0",
-     "@typescript-eslint/parser": "^5.0.0 || ^6.0.0",
[This new version has as peerDeps the v7](https://github.com/iamturns/eslint-config-airbnb-typescript/blob/master/package.json)
<details>
<br />
```bash
npm install @tablecheck/eslint-config@11.0.1-canary.118.12776181939.0
yarn add @tablecheck/eslint-config@11.0.1-canary.118.12776181939.0
```
</details>
=> fix: bump eslint-config-airbnb-typescript to 18.0.0
